name: Build German Artical Trainer
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt-get remove -y libunwind-14-dev || true
          
          # Added libharfbuzz-dev and libfribidi-dev at the end of this list
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev \
          libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
          build-essential ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libltdl-dev python3-dev libharfbuzz-dev libfribidi-dev
          
          pip3 install --user --upgrade Cython==0.29.33 virtualenv buildozer

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          if [ -d ".buildozer" ]; then buildozer android clean; fi
          buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GermanTrainer-APK
          path: bin/*.apk
